http://localhost:8080/item_category

--include 
--silent

Accept: application/json; 
Connection: keep-alive 
Content-Type: application/json; charset=utf-8 
User-Agent: VRC

GET 

#GET /3

#POST 
#{
#  #"id" : 1,
#  "name" : "test",
#  "category_id" : 1,
#  "status" : 1
#}

#PUT /2
#{
#"username" : "Pedro",
#  "password" : "asd",
#  "role" : "ADMIN"
#}


#DELETE /1

