http://localhost:8080/users

--include 
--silent

Accept: application/json; 
Connection: keep-alive 
Content-Type: application/json; charset=utf-8 
User-Agent: VRC

# NOTE: Probado
#GET 

# NOTE: Probado
#GET /2

# NOTE: Probado
#POST 
#{
#  #"id" : 1,
#  "username" : "test",
#  "password" : "test"
#  #"role" : "ADMIN"
#}

# NOTE: Probado
#PUT /2
#{
#"username" : "PedroS",
#  "password" : "asd",
#  "role" : "ADMIN"
#}


# NOTE: Probado
DELETE /2
